{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: astronomy-db-init
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
data:
  init.sh: |-
    {{- .Files.Get "files/postgresql/init.sh" | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astronomy-db
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "otel-demo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "otel-demo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}

          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.port }}
              protocol: TCP

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: astronomy-db-credentials
                  key: POSTGRES_PASSWORD

            - name: ASTRONOMY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: astronomy-db-credentials
                  key: ASTRONOMY_PASSWORD

            - name: MONITORING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: astronomy-db-credentials
                  key: MONITORING_PASSWORD

          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}

          volumeMounts:
            - name: init
              mountPath: /docker-entrypoint-initdb.d/init.sh
              subPath: init.sh
              readOnly: true

      volumes:
        - name: init
          configMap:
            name: astronomy-db-init
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: astronomy-db
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "otel-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
{{- end }}