{{- if and .Values.postgres.enabled .Values.postgres.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: astronomy-db
spec:
  podSelector:
    matchLabels:
      {{- include "otel-demo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: product-catalog

        - podSelector:
            matchLabels:
              app.kubernetes.io/component: accounting

      ports:
        - protocol: TCP
          port: 5432
{{- end }}
