apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames: [identity]
  selector:
    matchLabels: {app.kubernetes.io/name: keycloak}
  endpoints:
    - port: management
      path: /metrics
      interval: 30s
