apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-updater-git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: image-updater-git-creds
    creationPolicy: Owner
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd-image-updater-git-ssh-key
