apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  sslPolicy: ELBSecurityPolicy-TLS13-1-2-Res-PQ-2025-09
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: alb
