# Enable the AWS-managed controller that implements the demo NetworkPolicies.
# https://docs.aws.amazon.com/eks/latest/userguide/auto-net-pol.html
apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
  namespace: kube-system
data:
  enable-network-policy-controller: "true"
