apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-grafana-oidc
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: monitoring-grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: keycloak-credentials
        property: grafana_client_secret
