apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-grafana-db
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: monitoring-grafana-db
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: grafana-db-credentials
        property: host
    - secretKey: username
      remoteRef:
        key: grafana-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: grafana-db-credentials
        property: password
    - secretKey: secret_key
      remoteRef:
        key: grafana-db-credentials
        property: secret_key
