{{- range $name, $fields := dict
    "keycloak-runtime" (dict "db_url" "db_url" "username" "username" "password" "password" "bootstrap_client_secret" "bootstrap_client_secret")
    "keycloak-configuration" (dict "configuration_client_secret" "configuration_client_secret" "bootstrap_client_secret" "bootstrap_client_secret" "grafana_client_secret" "grafana_client_secret" "admin_username" "admin_username" "admin_password" "admin_password" "operator_username" "operator_username" "operator_password" "operator_password") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ $name }}
    creationPolicy: Owner
  data:
    {{- range $key, $property := $fields }}
    - secretKey: {{ $key }}
      remoteRef:
        key: keycloak-credentials
        property: {{ $property }}
    {{- end }}
{{- end }}
