{{- if (index .Values.services "product-catalog").enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: product-catalog-db
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: product-catalog-db
    creationPolicy: Owner

  data:
    - secretKey: connection-string
      remoteRef:
        key: product-catalog-db-connection-string
{{- end }}